# Amethyst - CircleCI File for CI
# Contributed by Capuccino
version: 2
jobs:
  build:
    docker:
      - image: chinodesuuu/ci-amethyst
    working_directory: ~/Amethyst
    steps:
      - checkout
      - run:
          command: |
           set -x 
           git clone https://github.com/Rapptz/discord.py --branch rewrite 
           mv discord.py/discord discord
      - run:
          command: |
           cloc --exclude-dir=discord --exclude-dir=discord.py .           
           python3 -m pip install flake8
           flake8 --exclude=discord,discord.py --show-source --max-line-length 120 . 
           python3 -m compileall -x discord.* .